config/routes.rb
Rails.application.routes.draw do
  # root
  root to: "items#index"

  # devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete :sign_out, to: 'devise/sessions#destroy'
  end

  # signup_controller
  resources :signup, only: [:index, :create] do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4'
      post 'pay'
      get 'done'
    end
  end

  # user_controller
  resource :users, only: :index do
    collection do
      get 'mypage'
      get 'profile'
      get 'identity'
      get 'logout'
    end
  end

  # card_controller
  resources :card, only: [:new, :show] do
    collection do
      get 'confirmation', to: 'card#confirmation'
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  # items_controller
  resources :items do
    collection do
      get 'sell'
    end
    
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  has_one :address
  has_one :card
  accepts_nested_attributes_for :address


  def self.find_for_oauth(auth)
    @user = User.where(uid: auth.uid, provider: auth.provider).first_or_create

    # @user = auth || User.where(email: auth.info.email).first_or_initialize(
    #   nickname: auth.info.name,
    #     email: auth.info.email
    # )
    # if @user.persisted?
    #   auth.user = user
    #   user.save
    # end
    # @user
    #これで動いたら下不要

    unless @user
      @user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        nickname: auth.info.name,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end
    @user
  end

  private

    def self.dummy_email(auth)
      "#{auth.uid}-#{auth.provider}@gmail.com"
    end

  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d!@#\$%\^\&*\)\(+=._-]{7,128}\z/i
  VALID_KATAKANA_REGEX = /\A[\p{katakana}\p{blank}ー－]+\z/
  VALID_PHONE_REGEX = /\A\d{10,11}\z/

  # step1バリデーション
  validates :nickname,          presence: true, length: { maximum: 20 }
  validates :email,             presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password,          presence: true, length: { minimum: 7, maximum: 128 }, format: { with: VALID_PASSWORD_REGEX }
  validates :family_name_kanji, presence: true
  validates :first_name_kanji,  presence: true
  validates :family_name_kana,  presence: true, format: { with: VALID_KATAKANA_REGEX }
  validates :first_name_kana,   presence: true, format: { with: VALID_KATAKANA_REGEX }
  validates :birthdate_year,    presence: true
  validates :birthdate_month,   presence: true
  validates :birthdate_day,     presence: true

  # step2バリデーション
  validates :phone_number,      presence: true, uniqueness: true, format: { with: VALID_PHONE_REGEX }

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from(:facebook)
  end

  def google_oauth2
    callback_from(:google)
  end

  def failure
    redirect_to root_path
  end

  private

  def callback_from(provider)
    provider = provider.to_s
    @user = User.find_for_oauth(request.env['omniauth.auth'])
  

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication

    else
      session[:nickname] = @user.nickname
      session[:email] = @user.email
      session[:password] = @user.password
      session[:provider] = @user.provider
      session[:uid] = @user.uid
      redirect_to step1_signup_index_url
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def mypage
  end

  def profile
  end

  def identity
  end

  def logout
  end
end

app/views/users/_mypage-side-bar.html.haml
.side-bar
  %nav.mypage-nav
    %ul.mypage-nav__list
      %li<
        = link_to mypage_users_path do
          マイページ
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<お知らせ
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<やることリスト
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<いいね！一覧
          = icon 'fas', 'chevron-right'
      %li<
        = link_to sell_items_path do
          出品する
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<出品した商品-出品中
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<出品した商品-取引中
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<出品した商品-売却済み
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<購入した商品-取引中
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<購入した商品-過去の取引
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<ニュース一覧
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<評価一覧
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<ガイド
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<お問い合わせ
          = icon 'fas', 'chevron-right'

    %h3.mypage-nav__title.bolb メルペイ
    %ul.mypage-nav__list
      %li<
        = link_to "#" do
          %del<売上・振込申請
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<ポイント
          = icon 'fas', 'chevron-right'

    %h3.mypage-nav__title.bolb 設定
    %ul.mypage-nav__list
      %li<
        = link_to profile_users_path do
          プロフィール
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<発送元・お届先住所変更
          = icon 'fas', 'chevron-right'
      %li<
        = link_to confirmation_card_index_path do
          支払い方法
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<メール/パスワード
          = icon 'fas', 'chevron-right'
      %li<
        = link_to identity_users_path do
          本人情報
          = icon 'fas', 'chevron-right'
      %li<
        = link_to "#" do
          %del<電話番号の確認
          = icon 'fas', 'chevron-right'
      %li<
        = link_to logout_users_path do
          ログアウト
          = icon 'fas', 'chevron-right'

app/views/users/identity.html.haml
= render 'show/main_header'
.box
  - breadcrumb :identity
  = breadcrumbs separator: " &rsaquo; "
.mypage-wrapper
  = render 'mypage-side-bar'
  .mypage-main
    %h2.chapter-head.bolb
      本人情報の登録
    %form.single-contents
      %p
        お客さまの本人情報をご登録ください。
        %br
        登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
      %p.text-right
        = link_to "#" do
          本人確認書類のアップロードについて
          = icon 'fas', 'chevron-right'
      .single-contents__content
        %label.bolb
          お名前
        %p
          メルカリ花子
      .single-contents__content
        %label.bolb
          お名前カナ
        %p
          メルカリハナコ
      .single-contents__content
        %label.bolb
          生年月日
        %p
          YYYY/MM/DD
      .single-contents__content
        %label.bolb
          郵便番号
        %span.form-arbitrary
          任意
        %input{ name: "zip-code", type: "text_field", placeholder: "例) 1234567", class: "input-text-field" }
      .single-contents__content
        %label.bolb
          都道府県
        %span.form-arbitrary
          任意
        .select-wrap
          = icon 'fas', 'chevron-down'
          %select{ name: "prefecture", class: "select" }
            %option --
            %option 北海道
            // active_hashの利用はコンフリクトの発生を考慮して出品ページの完了後に実装
      .single-contents__content
        %label.bolb
          市区町村
        %span.form-arbitrary
          任意
        %input{ name: "city", type: "text_field", placeholder: "例) 横浜市緑区", class: "input-text-field" }
      .single-contents__content
        %label.bolb
          番地
        %span.form-arbitrary
          任意
        %input{ name: "address1", type: "text_field", placeholder: "例) 青山1−1−1", class: "input-text-field" }
      .single-contents__content
        %label.bolb
          建物名
        %span.form-arbitrary
          任意
        %input{ name: "address2", type: "text_field", placeholder: "例) 柳ビル103", class: "input-text-field" }
      %input{ type: "submit", value: "登録する", class: "submit-btn" }
      %p.text-right
        = link_to "#" do
          本人情報の登録について
          = icon 'fas', 'chevron-right'
= render 'show/main_footer'

app/views/users/index.html.haml
.registration-wrapper
  = render "sub-header"
  = render "login"
  = render "registration-footer"

app/views/users/logout.html.haml
.wrapper
  = render 'show/main_header'
.box
  - breadcrumb :logout
  = breadcrumbs separator: " &rsaquo; "
.wrapper
  .mypage-wrapper
    = render "mypage-side-bar"
    .logout-submit
      .logout-submit__bar
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'logout-submit__bar logout-submit__bar__red submit'
  = render 'show/main_footer'

app/views/users/mypage.html.haml
= render 'show/main_header'
.box
  - breadcrumb :mypage
  = breadcrumbs separator: " &rsaquo; "
.mypage-wrapper
  = render 'mypage-side-bar'
  .mypage-main
    %section.mypage-main__user-icon
      = link_to "#" do
        = image_tag 'member_photo_noimage_thumb.png'
        %h2.bolb
          = current_user.nickname
        .number
          %p
            評価
            %span.bolb 0
          %p
            出品数
            %span.bolb 0

    %section.mypage-main__container
      .tabs
        %input#info{ checked: "checked", name: "tab-radio", type: "radio" }
        %label.tab-content{ for: "info" } お知らせ
        %input#todo{ name: "tab-radio", type: "radio" }
        %label.tab-content{ for: "todo" } やることリスト
        .clear-shadow
        .mypage-main__container__content.info
          .mypage-main__container__content__none.bolb
            現在、お知らせはありません
        .mypage-main__container__content.todo
          .mypage-main__container__content__none.bolb
            現在、やることリストはありません

    %section.mypage-main__container
      %h2.mypage-main__container__title.bolb
        購入した商品
      .tabs
        %input#trade{ checked: "checked", name: "tab-check", type: "radio" }
        %label.tab-content{ for: "trade" } 取引中
        %input#completion{ name: "tab-check", type: "radio" }
        %label.tab-content{ for: "completion" } 過去の取引
        .clear-shadow
        .mypage-main__container__content.trade
          .mypage-main__container__content__none.bolb
            取引中の商品がありません
        .mypage-main__container__content.completion
          .mypage-main__container__content__none.bolb
            過去に取引した商品がありません
= render 'show/main_footer'

app/views/users/profile.html.haml
= render 'show/main_header'
.box
  - breadcrumb :profile
  = breadcrumbs separator: " &rsaquo; "
.mypage-wrapper
  = render 'mypage-side-bar'
  .mypage-main
    %h2.chapter-head.bolb
      プロフィール
    %form.input-box
      .input-box__setting-icon
        = image_tag 'member_photo_noimage_thumb.png'
        %input{ name: "nickname", type: "text_field", placeholder: "例)AYA☆セール中", class: "input-box__setting-icon__text" }
      .input-box__profile
        %textarea{ name: "profile", class: "input-box__profile__area", placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪" }
        %input{ type: "submit", value: "変更する", class: "submit-btn" }
= render 'show/main_footer'