config/routes.rb
Rails.application.routes.draw do
  # root
  root to: "items#index"

  # devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete :sign_out, to: 'devise/sessions#destroy'
  end

  # signup_controller
  resources :signup, only: [:index, :create] do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4'
      post 'pay'
      get 'done'
    end
  end

  # user_controller
  resource :users, only: :index do
    collection do
      get 'mypage'
      get 'profile'
      get 'identity'
      get 'logout'
    end
  end

  # card_controller
  resources :card, only: [:new, :show] do
    collection do
      get 'confirmation', to: 'card#confirmation'
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  # items_controller
  resources :items do
    collection do
      get 'sell'
    end
    
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  has_many_attached :images
  belongs_to :user

  validates :item_name,        presence: true, length: { maximum: 40 }
  validates :explain,          presence: true
  validates :category,         presence: true
  validates :size,             presence: true
  validates :condition,        presence: true
  validates :postage,          presence: true
  validates :shipping_method,  presence: true
  validates :prefecture_id,    presence: true
  validates :shipping_days,    presence: true
  validates :price,            numericality: {greater_than_or_equal_to: 300}
  validates :price,            numericality: {less_than_or_equal_to: 9999999}

  validate :images_presence

  private

  def images_presence
    if images.attached?
      images.each do |image|
        if !image.content_type.in?(%('image/jpg image/jpeg image/png'))
          image.purge
          errors.add(:images, 'には画像ファイルを添付してください')
        end
      end
    else
      errors.add(:images, '画像がありません')
    end
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.includes(:user).order("created_at DESC").with_attached_images.limit(10)
  end

  def show
  end

  def sell
    @item = Item.new
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item), notice: '商品を編集しました'
    else
      render :edit
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :sell
    end
  end

  def destroy
    if@item.destroy
      redirect_to items_url, notice: '商品を削除しました'
    else
      render
    end
  end

  private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(
        :item_name,
        :explain,
        :category,
        :size,
        :brand,
        :condition,
        :postage,
        :shipping_method,
        :prefecture_id,
        :shipping_days,
        :price,
        :trade_state,
        images: []
      ).merge(user_id: current_user.id)
    end
end

app/views/items/_error-message.html.haml
- if item.errors.any?
  - unless item.valid?
    - if errors = item.errors.full_messages_for(column.to_sym)
      %ul.error-text
        - errors.each do |error|
          %li= error

app/views/items/_purchase.html.haml
.registration-wrapper
  = render "/shared/sub-header"
  %h2.single-head.bolb
    購入内容の確認
  .purchase-main
    .purchase-main__buy-item
      .inner-box
        = image_tag 'text_netabare_chuui.png'
        .inner-box__right
          %p
            商品名
          %p.bolb
            ￥8,000（税込み）送料込み
    .purchase-main__content
      .inner-box
        .inner-box__left.bolb
          %p
            支払い金額
        .inner-box__right.bolb.pay
          ￥8,000
      %input{ type: "checkbox", id: "point" }
      %label{ for: "point" }
        ポイントを使用(所持ポイント:P0)
    .purchase-main__content
      %p.bolb
        支払い方法
      %p
        = link_to "#" do
          = icon 'fas', 'plus-circle', class: 'link-icon'
          登録してください
    .purchase-main__content
      .inner-box
        .inner-box__left.bolb
          配送先
        .inner-box__right
          = link_to "変更する", "#"
      %p
        〒163-8001
        %br 東京都新宿区西新宿２丁目８−１
        東京都庁
    .inner-box
      %input{type: "submit", value: "購入する", class: "submit-btn"}
  = render "/shared/sub-footer"

app/views/items/_sell.html.haml
.sell-main
  %h2.sell-main__title.bolb
    商品の情報を入力
  = form_with model: @item, local: true, url: items_path, method: 'POST', class: 'sell-main__form' do |f|
    //商品画像、投稿エリア↓↓↓
    .sell-main__form__upload
      %h3.sell-main__form__upload__head.bolb
        出品画像
      %span.form-require
        必須
      %p
        最大10枚までアップロードできます
      //ファイルフィールド（画像アップロード）↓↓↓
      = f.label :images do
        .sell-main__form__upload__box
          ドラッグアンドドロップ
          %br
          またはクリックしてファイルをアップロード
          = f.file_field :images, multiple: true, class: 'file_field'
      - if @item.errors.full_messages_for(:images).any?
        = render 'error-message', item: @item, column: "images"
    .sell-main__form__content
      //商品名、入力エリア↓↓↓
      .sell-main__form__content__box-label--first
        %label.bolb
          商品名
        %span.form-require
          必須
      = f.text_field :item_name,
        placeholder: "商品名（必須 40文字まで)",
        autofocus: true, class: 'sell-main__form__content__text-field'
      - if @item.errors.full_messages_for(:item_name).any?
        = render 'error-message', item: @item, column: "item_name"
      //商品説明、入力エリア↓↓↓
      .sell-main__form__content__box-label
        %label.bolb
          商品の説明
        %span.form-require
          必須
      = f.text_area :explain,
          placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。",
          autofocus: true,
          class: 'sell-main__form__content__text-area'
      - if @item.errors.full_messages_for(:explain).any?
        = render 'error-message', item: @item, column: "explain"
    .sell-main__form__content.space-between
      %h3.sell-main__form__content__head.bolb
        商品の詳細
      .sell-main__form__content__right
        //カテゴリ、選択エリア↓↓↓
        .sell-main__form__content__form-label--first
          %label.bolb
            カテゴリー
          %span.form-require
            必須
        = f.select :category,
          [["レディース", "レディース"],
           ["メンズ", "メンズ"],
           ["ベビー・キッズ", "ベビー・キッズ"],
           ["インテリア・住まい・小物", "インテリア・住まい・小物"],
           ["本・音楽・ゲーム", "本・音楽・ゲーム"],
           ["おもちゃ・ホビー・グッズ", "おもちゃ・ホビー・グッズ"],
           ["コスメ・香水・美容", "コスメ・香水・美容"],
           ["家電・スマホ・カメラ", "家電・スマホ・カメラ"],
           ["スポーツ・レジャー", "スポーツ・レジャー"],
           ["ハンドメイド", "ハンドメイド"],
           ["チケット", "チケット"],
           ["自動車・オートバイ", "自動車・オートバイ"],
           ["その他", "その他"]],
          { prompt: "--" },
          { autofocus: 'true',
            class: "sell-main__form__content__select" }
        - if @item.errors.full_messages_for(:category).any?
          = render 'error-message', item: @item, column: "category"
        //サイズ、選択エリア↓↓↓
        .sell-main__form__content__form-label
          %label.bolb
            サイズ
          %span.form-require
            必須
        = f.select :size,
          [["S", "S"],
           ["M", "M"],
           ["L", "L"]],
          { prompt: "--" },
          { autofocus: 'true',
            class: "sell-main__form__content__select" }
        - if @item.errors.full_messages_for(:size).any?
          = render 'error-message', item: @item, column: "size"
        //ブランド、入力エリア↓↓↓
        .sell-main__form__content__form-label
          %label.bolb
            ブランド
          %span.form-arbitrary
            任意
        = f.text_field :brand,
            placeholder: "例）シャネル",
            autofocus: true, class: 'sell-main__form__content__select'
        //商品の状態、選択エリア↓↓↓
        .sell-main__form__content__form-label
          %label.bolb
            商品の状態
          %span.form-require
            必須
        = f.select :condition,
          [["新品、未使用", "新品、未使用"],
           ["未使用に近い", "未使用に近い"],
           ["目立った傷や汚れなし", "目立った傷や汚れなし"],
           ["やや傷や汚れあり", "やや傷や汚れあり"],
           ["傷や汚れあり", "傷や汚れあり"],
           ["全体的に状態が悪い", "全体的に状態が悪い"]],
          { prompt: "--" },
          { autofocus: 'true',
            class: "sell-main__form__content__select" }
        - if @item.errors.full_messages_for(:condition).any?
          = render 'error-message', item: @item, column: "condition"
    .sell-main__form__content.space-between
      %h3.sell-main__form__content__head.bolb
        配送について
        %span.form-question
          ?
      .sell-main__form__content__right
        //配送料の負担、選択エリア↓↓↓
        .sell-main__form__content__form-label--first
          %label.bolb
            配送料の負担
          %span.form-require
            必須
        = f.select :postage,
          [["送料込み(出品者負担)", "送料込み(出品者負担)"],
           ["着払い(購入者負担)", "着払い(購入者負担)"]],
          { prompt: "--" },
          { autofocus: 'true',
            class: "sell-main__form__content__select" }
        - if @item.errors.full_messages_for(:postage).any?
          = render 'error-message', item: @item, column: "postage"
        //発送の方法、選択エリア↓↓↓
        .sell-main__form__content__form-label
          %label.bolb
            発送の方法
          %span.form-require
            必須
        = f.select :shipping_method,
          [["未定", "未定"],
           ["らくらくメルカリ便", "らくらくメルカリ便"],
           ["ゆうメール", "ゆうメール"],
           ["レターパック", "レターパック"],
           ["普通郵便(定形、定形外)", "普通郵便(定形、定形外)"],
           ["クロネコヤマト", "クロネコヤマト"],
           ["ゆうパック", "ゆうパック"],
           ["クリックポスト", "クリックポスト"],
           ["ゆうパケット", "ゆうパケット"]],
          { prompt: "--" },
          { autofocus: 'true',
            class: "sell-main__form__content__select" }
        - if @item.errors.full_messages_for(:shipping_method).any?
          = render 'error-message', item: @item, column: "shipping_method"
        //発送元の地域、選択エリア↓↓↓
        .sell-main__form__content__form-label
          %label.bolb
            発送元の地域
          %span.form-require
            必須
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name,
         { prompt: "--" },
         { class: 'sell-main__form__content__select' }
        - if @item.errors.full_messages_for(:prefecture_id).any?
          = render 'error-message', item: @item, column: "prefecture_id"
        //発送までの日数、選択エリア↓↓↓
        .sell-main__form__content__form-label
          %label.bolb
            発送までの日数
          %span.form-require
            必須
        = f.select :shipping_days,
         [["1~2日で発送", "1~2日で発送"],
          ["2~3日で発送", "2~3日で発送"],
          ["4~7日で発送", "4~7日で発送"]],
         { prompt: "--" },
         { autofocus: 'true',
           class: "sell-main__form__content__select" }
        - if @item.errors.full_messages_for(:shipping_days).any?
          = render 'error-message', item: @item, column: "shipping_days"

    .sell-main__form__content.space-between
      %h3.sell-main__form__content__head.bolb
        販売価格(300〜9,999,999)
        %span.form-question
          ?
      %ul.sell-main__form__content__right
        //配送料の負担エリア↓↓↓
        %li.sell-main__form__content__price-first.space-between
          .sell-main__form__content__price-first__label-input
            %label.bolb
              価格
            %span.form-require
              必須
          .sell-main__form__content__price-first__input
            ¥
            //入力エリア↓↓↓
            = f.text_field :price, placeholder: "例）300",
              autofocus: true,
              class: 'sell-main__form__content__price-first__text-field'
            - if @item.errors.full_messages_for(:price).any?
              = render 'error-message', item: @item, column: "price"
        //販売手数料エリア↓↓↓
        %li.sell-main__form__content__price.space-between
          .sell-main__form__content__price__label-fee
            %label
              販売手数料(10%)
          .sell-main__form__content__price__fee
            #fee
        //販売利益エリア↓↓↓
        %li.sell-main__form__content__price.space-between.bolb
          .sell-main__form__content__price__label-profit
            %label
              販売利益
          .sell-main__form__content__price__profit
            #seller_profit
    .sell-main__form__content
      %p
        %a{ href:'#' }>禁止されている出品
        、
        %a{ href:'#' }>行為
        を必ずご確認ください。
      %p
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        %a{ href:'#' }>偽ブランドの販売
        は犯罪であり処罰される可能性があります。
      %p
        また、出品をもちまして
        %a{ href:'#' }>加盟店規約
        に同意したことになります。
      .sell-main__form__content__box
        = f.hidden_field :trade_state, value: "出品中"
        = f.submit value: "出品する", class: 'submit-btn__go'
        = link_to :back, class: 'submit-btn__back' do
          もどる

app/views/items/index.html.haml
.wrapper
  = render 'show/main_header'
  .main-content
    .main-content__text-area
      .main-slide-show
        = link_to image_tag('top-banner1.jpg'), '#'
        //コンテンツ部分 スライドショーから
        .main-slide-show-list
      //いいね！した商品一覧　いいね機能未実装のためコメントアウト
      -# .main-like-product
      -#   .main-like-product__top
      -#     .main-like-product-top-message
      -#       いいね！した商品
      -#     .main-like-product-all-link
      -#       = link_to "すべて見る", "#"
      -#   .main-like-bottom-product
      -#     .main-like-bottom-product-image
      -#       = link_to image_tag('likeimage1.jpg'),"#"
      -#       .main-like-bottom-product-image__price
      -#         ¥1,000
      -#     .main-like-bottom-product-image__text
      -#       ランプ
      -#     .main-like-bottom-product-image
      -#       = link_to image_tag('likeimage1.jpg'), '#'
      -#       .main-like-bottom-product-image__price
      -#         ¥1,000
      -#     .main-like-bottom-product-image__text
      -#       ランプ
      -#     .main-like-bottom-product-image
      -#       = link_to image_tag('mercarineko.jpg'), '#'
      -#       .main-like-bottom-product-image__price
      -#         ¥1,000,000
      -#     .main-like-bottom-product-image
      -#       = link_to image_tag('mercarineko.jpg'), '#'
      -#       .main-like-bottom-product-image__price
      -#         ¥1,000,000
      .main-popular-category-area
        .main-popular-category-area__message
          人気のカテゴリー
        .main-popular-category-area__tag
          %ul
            %li レディース
            %li メンズ
            %li 家電・スマホ・カメラ
            %li おもちゃ・ホビー・グッズ
      .ladies-new-items
        .popular-new-item__area
          .popular-new-item-top
            .ladies-new-item-top__left-text
              レディース新着アイテム
            .ladies-new-item-top__right-text
              = link_to "もっと見る", "#"
          .ladies-new-item-product
            .ladies-new-item-product__list
              - @items.each do |item|
                .ladies-new-item-product-list-item
                  = link_to item_path(item.id) do
                    = image_tag item.images[0], size: "184x188"
                  .ladies-new-item-product-image__price
                    ￥#{ item.price }
                  .ladies-new-item-product-image__text
                    #{ item.item_name }

      .ladies-new-items
        .popular-new-item__area
          .popular-new-item-top
            .ladies-new-item-top__left-text
              メンズ新着アイテム
            .ladies-new-item-top__right-text
              = link_to "もっと見る", "#"
          .ladies-new-item-product
            .ladies-new-item-product__list
              - @items.each do |item|
                .ladies-new-item-product-list-item
                  = link_to item_path(item.id) do
                    = image_tag item.images[0], size: "184x188"
                  .ladies-new-item-product-image__price
                    ￥#{ item.price }
                  .ladies-new-item-product-image__text
                    #{ item.item_name }

      .ladies-new-items
        .popular-new-item__area
          .popular-new-item-top
            .ladies-new-item-top__left-text
              家電・スマホ・カメラ新着アイテム
            .ladies-new-item-top__right-text
              = link_to "もっと見る", "#"
          .ladies-new-item-product
            .ladies-new-item-product__list
              - @items.each do |item|
                .ladies-new-item-product-list-item
                  = link_to item_path(item.id) do
                    = image_tag item.images[0], size: "184x188"
                  .ladies-new-item-product-image__price
                    ￥#{ item.price }
                  .ladies-new-item-product-image__text
                    #{ item.item_name }

      .ladies-new-items
        .popular-new-item__area
          .popular-new-item-top
            .ladies-new-item-top__left-text
              おもちゃ・ホビー・グッズ新着アイテム
            .ladies-new-item-top__right-text
              = link_to "もっと見る", "#"
          .ladies-new-item-product
            .ladies-new-item-product__list
              - @items.each do |item|
                .ladies-new-item-product-list-item
                  = link_to item_path(item.id) do
                    = image_tag item.images[0], size: "184x188"
                  .ladies-new-item-product-image__price
                    ￥#{ item.price }
                  .ladies-new-item-product-image__text
                    #{ item.item_name }

      .main-popular-category-area
        .main-popular-category-area__message
          人気のブランド
        .main-popular-category-area__tag
          %ul
            %li シャネル
            %li ルイヴィトン
            %li シュプリーム
            %li ナイキ

      .ladies-new-items
        .popular-new-item__area
          .popular-new-item-top
            .ladies-new-item-top__left-text
              シャネル新着アイテム
            .ladies-new-item-top__right-text
              = link_to "もっと見る", "#"
          .ladies-new-item-product
            .ladies-new-item-product__list
              - @items.each do |item|
                .ladies-new-item-product-list-item
                  = link_to item_path(item.id) do
                    = image_tag item.images[0], size: "184x188"
                  .ladies-new-item-product-image__price
                    ￥#{ item.price }
                  .ladies-new-item-product-image__text
                    #{ item.item_name }

      .ladies-new-items
        .popular-new-item__area
          .popular-new-item-top
            .ladies-new-item-top__left-text
              ルイヴィトン新着アイテム
            .ladies-new-item-top__right-text
              = link_to "もっと見る", "#"
          .ladies-new-item-product
            .ladies-new-item-product__list
              - @items.each do |item|
                .ladies-new-item-product-list-item
                  = link_to item_path(item.id) do
                    = image_tag item.images[0], size: "184x188"
                  .ladies-new-item-product-image__price
                    ￥#{ item.price }
                  .ladies-new-item-product-image__text
                    #{ item.item_name }

      .ladies-new-items
        .popular-new-item__area
          .popular-new-item-top
            .ladies-new-item-top__left-text
              シュプリーム新着アイテム
            .ladies-new-item-top__right-text
              = link_to "もっと見る", "#"
          .ladies-new-item-product
            .ladies-new-item-product__list
              - @items.each do |item|
                .ladies-new-item-product-list-item
                  = link_to item_path(item.id) do
                    = image_tag item.images[0], size: "184x188"
                  .ladies-new-item-product-image__price
                    ￥#{ item.price }
                  .ladies-new-item-product-image__text
                    #{ item.item_name }

      .ladies-new-items
        .popular-new-item__area
          .popular-new-item-top
            .ladies-new-item-top__left-text
              ナイキ新着アイテム
            .ladies-new-item-top__right-text
              = link_to "もっと見る", "#"
          .ladies-new-item-product
            .ladies-new-item-product__list
              - @items.each do |item|
                .ladies-new-item-product-list-item
                  = link_to item_path(item.id) do
                    = image_tag item.images[0], size: "184x188"
                  .ladies-new-item-product-image__price
                    ￥#{ item.price }
                  .ladies-new-item-product-image__text
                    #{ item.item_name }

  .on-footer-image
    = image_tag "footer1.jpg"
    .on-footer-image__app
      .on-footer-image__top-text
        スマホで簡単フリマアプリ
      .on-footer-image__bottom-text
        今すぐ無料ダウンロード
      %br
      .on-footer-image__app-group
        .on-footer-image-mercari-logo
          = image_tag "mercari-logo-white.svg"
        .on-footer-image-app-logo
          = image_tag "appstore.svg"
        .on-footer-image__google-logo
          = image_tag "googleplay.svg"
    .on-footer-image__mercari-app-image
      = image_tag "download-app.png"

  .top-seller-btn
    - if user_signed_in?
      = link_to sell_items_path, class: "top-seller-btn-link" do
        出品
        %br
        = image_tag 'camera_icon.jpg', class: "camera_icon"
    - else
      = link_to new_user_session_path, class: "top-seller-btn-link" do
        出品
        %br
        = image_tag 'camera_icon.jpg', class: "camera_icon"

  = render 'show/main_footer'

app/views/items/sell.html.haml
.registration-wrapper
  = render "shared/sub-header"
.container
  = render "sell"
.registration-wrapper
  = render "shared/sub-footer"

app/views/items/show.html.haml
= render "show/main_header"

.item-box-container
  .h1.item-name
    = @item.item_name
  %p.item-wording
  #{@item.item_name}を出品したのは、
  %span
    = link_to @item.user.nickname, "#"
  です。
  %span
    = link_to @item.category, "#"
  の商品で、#{@item.prefecture.name}から#{@item.shipping_days}で発送されます。
  .item-main-content
    .item-photo
      .item-photo__carousel
        .item-photo__carousel__outer
          - if @item.images.attached?
            - @item.images.each do |image|
              = image_tag image, class:"item-photo__carousel__outer"
          .item-photo__carousel__outer__disabled
        .outer-dots
          .outer-dots__1
            - @item.images.each.with_index do |image, i|
              = image_tag image, class:"outer-dots__1"
    %table.item-detail-table
      %tbody
        %tr
          %th 出品者
          %td
            = link_to @item.user.nickname, "#"
            %span
              .item-user-ratings
                %i.far.fa-grin
                %span 1
              .item-user-ratings
                %i.far.fa-frown
                %span 0
              .item-user-ratings
                %i.far.fa-tired
                %span 0
        %tr
          %th カテゴリー
          %td.item-detail-main-category
            = link_to @item.category, "#"
            .item-detail-table-sub-category
              = link_to "その他", "#"
            .item-detail-table-sub-sub-category
              = link_to "その他", "#"
        %tr
          %th ブランド
          %td
            = link_to @item.brand, "#"
        %tr
          %th 商品のサイズ
          %td= @item.size
        %tr
          %th 商品の状態
          %td= @item.condition
        %tr
          %th 配送料の負担
          %td= @item.postage
        %tr
          %th 配送の方法
          %td= @item.shipping_method
        %tr
          %th 配送元地域
          %td= link_to @item.prefecture.name, "#"
        %tr
          %th 発送日の目安
          %td= @item.shipping_days

  .item-price-box.text-center
    %span.item-price.bold
      ¥
      = @item.price
    %span.item-tax
      (税込)
    %span.item-shipping-fee
      = @item.postage
  - if user_signed_in? && current_user.id == @item.user.id
    = link_to "商品の編集", edit_item_path(@item), class: "item-buy-btn"
    - if @item.trade_state == "出品中"
      = form_with model: @item, local: true, url: item_path, loclal: true do |f|
        = f.hidden_field :trade_state, value: "出品停止中"
        = f.submit '出品を一旦停止する', class: 'item-buy-btn-gry'
    - elsif @item.trade_state == "出品停止中"
      = form_with model: @item, local: true, url: item_path, loclal: true do |f|
        = f.hidden_field :trade_state, value: "出品中"
        = f.submit '出品を再開する', class: 'item-buy-btn'
    = link_to 'この商品を削除する', item_path, method: :delete, data: { confirm: '本当に削除しますか？' }, class: "item-buy-btn-gry"
  - else
    = link_to "購入画面に進む", item_purchase_index_path(@item.id), class: "item-buy-btn"
  .item-description
  %p.item-description-inner
    = @item.explain

  .item-button-container
    .item-button-container__left
      %button.item-button.item-button-like
        %i.far.fa-heart
        %span いいね!
        %span.fade-in-down 5
      %a.item-button-report
        %i.fas.fa-flag
        %span 不適切な商品の報告
    .item-button-right
      %i.fas.fa-user-lock
      %span あんしん・あんぜんへの取り組み

= render "show/main_footer"