config/routes.rb
Rails.application.routes.draw do
  # root
  root to: "items#index"

  # devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete :sign_out, to: 'devise/sessions#destroy'
  end

  # signup_controller
  resources :signup, only: [:index, :create] do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4'
      post 'pay'
      get 'done'
    end
  end

  # user_controller
  resource :users, only: :index do
    collection do
      get 'mypage'
      get 'profile'
      get 'identity'
      get 'logout'
    end
  end

  # card_controller
  resources :card, only: [:new, :show] do
    collection do
      get 'confirmation', to: 'card#confirmation'
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  # items_controller
  resources :items do
    collection do
      get 'sell'
    end
    
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
  end

end

app/views/show/_main_footer.html.haml
.footer
  .footer-text-area
    .footer-cell1
      %h2.footer-head メルカリについて
      %ul
        %li
          = link_to '会社概要（運営会社）', '#'
        %li
          = link_to '採用情報', '#'
        %li
          = link_to 'プレスリリース', '#'
        %li
          = link_to '公式ブログ', '#'
        %li
          = link_to 'メルカリロゴ利用ガイドライン', '#'
      %ul.social-link
        %li.footer-social-link-twitter
          = link_to image_tag("twittericon.png"),'https://twitter.com/mercari_jp'
        %li.footer-social-link-facebook
          = link_to image_tag('facebook.jpeg'),'https://www.facebook.com/mercarijp'
    .footer-cell2
      %h2.footer-head
        ヘルプガイド
        %ul
          %li
            = link_to 'メルカリガイド', '#'
          %li
            = link_to 'らくらくメルカリ便', '#'
          %li
            = link_to 'ゆうゆうメルカリ便', '#'
          %li
            = link_to '大型メルカリ便', '#'
          %li
            = link_to '車体取引ガイド', '#'
          %li
            = link_to 'メルカリあんしん・あんぜん宣言！', '#'
          %li
            = link_to '偽ブランド品撲滅への取り組み', '#'
          %li
            = link_to 'メルカリボックス', '#'
    .footer-cell3
      %h2.footer-head
        プライバシーと利用規約
        %ul
          %li
            = link_to 'プライバシーポリシー', '#'
          %li
            = link_to 'メルカリ利用規約', '#'
          %li
            = link_to 'あんしんスマホサポート制度に関する利用特約', '#'
          %li
            = link_to 'コンプライアンスポリシー', '#'
      .inner-footer-cell
        %ul
          %li
            = link_to '個人データの安全管理に係る基本方針', '#'
          %li
            = link_to '特定商取引に関する表記', '#'
          %li
            = link_to '資金決済法に基づく表示', '#'
          %li
            = link_to '法令順守と犯罪抑止のために', '#'
    .footer-cell4
      %h2.footer-head 国
      %ul
        %li
          = link_to '日本', '#'
        %li
          = link_to 'United States', '#'
  .footer-bottom
    .footer-bottom__logo
      = link_to image_tag('mercari-logo-white.svg'), root_path
    .footer-bottom__copyright
      &copy; Fmarket, Inc.

app/views/show/_main_header.html.haml
.top-page
  .header
    .header__content
      .header-up-content
        .header-up-content__logo
          = link_to image_tag('fmarket_logo_red.svg'), root_path
        .header-up-content__form
          = form_with url: '#', local: true do |f|
            = f.label :search do
              = f.text_field :search, name: "keyword", placeholder: "何かお探しですか？", type: "search", value: "", class: 'header-up-content__form-area'
              %i.fa.fa-search
      .header-bottom
        .left-header-bottom
          .left-header-bottom__category
            = link_to 'カテゴリーから探す', '#',class: "category_btn"
          .left-header-bottom__brand
            = link_to 'ブランドから探す', '#',class: "brand_btn"
        .right-header-bottom
          - if user_signed_in?
            .top-log-in
              = link_to 'マイページ', mypage_users_path, class: "top-log-in__logo"
          - else
            .top-new-sign-up-btn
              = link_to '新規登録', signup_index_path, method: :get, class: "top-new-sign-up-btn__logo"
            .top-log-in
              = link_to 'ログイン', new_user_session_path, class: "top-log-in__logo"

app/views/show/detail_content.html.haml
= render "main_header"

.item-box-container
  .h1.item-name
    = @item.item_name
  %p.item-wording
  #{@item.item_name}を出品したのは、
  %span
    = link_to "#{@user.nickname}", "#"
  です。
  %span
    = link_to "#{@item.category}", "#"
  の商品で、#{@prefecture.name}から#{@item.shipping_days}で発送されます。
  .item-main-content
    .item-photo
      .item-photo__carousel
        .item-photo__carousel__outer
          - if @item.images.attached?
            - @item.images.each do |image|
              = image_tag image, class:"item-photo__carousel__outer"
          .item-photo__carousel__outer__disabled
        .outer-dots
          .outer-dots__1
            - @item.images.each.with_index do |image, i|
              = image_tag image, class:"outer-dots__1"
              
    %table.item-detail-table
      %tbody
        %tr
          %th 出品者
          %td
            = link_to "#{@user.nickname}", "#"
            %span
              .item-user-ratings
                %i.far.fa-grin
                %span 1
              .item-user-ratings
                %i.far.fa-frown
                %span 0
              .item-user-ratings
                %i.far.fa-tired
                %span 0
        %tr
          %th カテゴリー
          %td.item-detail-main-category
            = link_to "#{@item.category}", "#"
            .item-detail-table-sub-category
              = link_to "その他", "#"
            .item-detail-table-sub-sub-category
              = link_to "その他", "#"
        %tr
          %th ブランド
          %td
            = link_to "#{@item.brand}", "#"
        %tr
          %th 商品のサイズ
          %td #{@item.size}
        %tr
          %th 商品の状態
          %td #{@item.condition}
        %tr
          %th 配送料の負担
          %td #{@item.postage}
        %tr
          %th 配送の方法
          %td #{@item.shipping_method}
        %tr
          %th 配送元地域
          %td
            = link_to "#{@prefecture.name}", "#"
        %tr
          %th 発送日の目安
          %td #{@item.shipping_days}

  .item-price-box.text-center
    %span.item-price.bold ¥#{@item.price}
    %span.item-tax (税込)
    %span.item-shipping-fee #{@item.postage}
  .item-buy-btn
    = link_to "購入画面に進む", "#"

  .item-description
  %p.item-description-inner #{@item.explain}

  .item-button-container
    .item-button-container__left
      %button.item-button.item-button-like
        %i.far.fa-heart
        %span いいね!
        %span.fade-in-down 5
      %a.item-button-report
        %i.fas.fa-flag
        %span 不適切な商品の報告
    .item-button-right
      %i.fas.fa-user-lock
      %span あんしん・あんぜんへの取り組み

= render "main_footer"