config/routes.rb
Rails.application.routes.draw do
  # root
  root to: "items#index"

  # devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete :sign_out, to: 'devise/sessions#destroy'
  end

  # signup_controller
  resources :signup, only: [:index, :create] do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4'
      post 'pay'
      get 'done'
    end
  end

  # user_controller
  resource :users, only: :index do
    collection do
      get 'mypage'
      get 'profile'
      get 'identity'
      get 'logout'
    end
  end

  # card_controller
  resources :card, only: [:new, :show] do
    collection do
      get 'confirmation', to: 'card#confirmation'
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  # items_controller
  resources :items do
    collection do
      get 'sell'
    end
    
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
  end

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require "payjp"
  before_action :authenticate_user!
  before_action :set_card, only: [:delete, :show, :confirmation]
  before_action :set_payjp_info, only: [:pay, :delete, :show]

  def new
  end

  def pay
    if params['payjp-token'].blank?
      redirect_to action: "confirmation"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token']
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete
    if @card.present?
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      redirect_to action: "confirmation"
  end

  def show
    if @card.blank?
      redirect_to action: "confirmation" 
    else
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def confirmation
    redirect_to action: "show" if @card.present?
  end

  private

  def set_card
    @card = current_user.card
  end

  def set_payjp_info
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
  end
end

app/views/card/confirmation.html.haml
.wrapper
  = render 'show/main_header'
  .box
    - breadcrumb :card_index
    = breadcrumbs separator: " &rsaquo; "
  .mypage-wrapper
    = render "users/mypage-side-bar"
    .main__content.clearfix
      .main__content__right
        %section.main__content__right__all
          %h2.main__content__right__head 支払い方法
          .main__content__right__head__inner
            %section
              .main__content__center
                %h3.main__content__sub__head クレジットカード一覧
              %ul.settings__payment__list
            %section.settings__add__card
              .single__content
                .submit__button
                  %i.fas.fa-credit-card
                    = link_to new_card_path, class: "creditbtn" do
                      クレジットカードを追加する
            .settings__not__regist
              = link_to "#", class: 'credittext' do
                支払い方法について>
  = render 'show/main_footer'

app/views/card/new.html.haml
.wrapper
  = render 'show/main_header'
  .box
    - breadcrumb :new_card
    = breadcrumbs separator: " &rsaquo; "
  .mypage-wrapper
    = render "users/mypage-side-bar"
    .mypage-main
      %h2.chapter-head.bolb
        クレジットカード情報入力
      = form_with model: @card, url: pay_card_index_path, method: :post, name: 'inputForm', id: 'charge-form', class: 'card-form', novalidate: 'novalidate', local: true do |f|
        .card-form__content
          = f.label :card_num, class: 'bolb' do
            カード番号
          %span.form-necessary
            必須
          = f.text_field :card_number, id: 'card_number', placeholder: '半角数字のみ', maxlength: '19', class: 'input-text-field'
          = image_tag 'visa.svg', width: '49', height: '20'
          = image_tag 'master-card.svg', width: '34', height: '20'
          = image_tag 'saison-card.svg', width: '30', height: '20'
          = image_tag 'jcb.svg', width: '32', height: '20'
          = image_tag 'american_express.svg', width: '21', height: '20'
          = image_tag 'dinersclub.svg', width: '32', height: '20'
          = image_tag 'discover.svg', width: '32', height: '20'
        .card-form__content
          = f.label :month, class: 'bolb' do
            有効期限
          %span.form-necessary
            必須
          .card-form__content__division
            .select-wrap
              = icon 'fas', 'chevron-down', class: 'select-wrap__icon2'
              = f.select :exp_month, [["01",1], ["02",2], ["03",3], ["04",4], ["05",5], ["06",6], ["07",7], ["08",8], ["09",9], ["10",10], ["11",11], ["12",12]], {}, id: 'exp_month', class: 'select-credit'
              %span
                月
            .select-wrap
              = icon 'fas', 'chevron-down', class: 'select-wrap__icon2'
              = f.select :exp_year,[["19",2019], ["20",2020], ["21",2021], ["22",2022], ["23",2023], ["24",2024], ["25",2025], ["26",2026], ["27",2027], ["28",2028], ["29",2029]], {}, id: 'exp_year', class: 'select-credit'
              %span
                年
        .card-form__content
          = f.label :code, class: 'bolb' do
            セキュリティーコード
          %span.form-necessary
            必須
          = f.text_field :cvc, id: 'cvc', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: '4', class: 'input-text-field'
          #card_token
        .card-form__content
          = f.submit '追加する', id: 'token_submit', class: "submit-btn"
          %p.text-right
            = link_to "#" do
              = icon 'fas', 'question-circle'
              カード裏面の番号とは？
  = render 'show/main_footer'

app/views/card/show.html.haml
.wrapper
  = render 'show/main_header'
  .mypage-wrapper
    = render "users/mypage-side-bar"
    .mypage-main
      %h2.chapter-head.bolb
        クレジットカード情報入力
      .card-form
        .card-form__content
          .card-form__content__division
            .content-wrap
              %h3.sub-head.bolb
                クレジットカード一覧
              = image_tag 'jcb.svg', width: '26', height: '20', alt: 'jcb'
              %br
              = "**** **** **** " + @default_card_information.last4
              %br
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              = exp_month + " / " + exp_year
            .content-wrap
              = form_with model: @card, url: delete_card_index_path, method: :post, local: true do |f|
                = f.submit '削除する', class: "delete-submit"
        .border
        %p.text-right
          = link_to "#" do
            支払い方法について
  = render 'show/main_footer'